Algoritmo "IDADE"


Var
     nome1, nome2: caractere
     idade1, idade2: inteiro
     media: real


Inicio

      Escreval ("Dados da primeira pessoa: ")
      Escreva ("Nome: ")
      Leia (nome1)
      escreva ("Idade: ")
      Leia (idade1)
      escreval ("Dados da segunda pessoa")
      escreva ("Nome: ")
      leia (nome2)
      escreva ("Idade: ")
      leia (idade2)
      
      media <- (idade1 + idade2) /2
      
      Escreval ("A idade media de ", nome1, " e ", nome2, " eh de ",media, " Anos")


Fimalgoritmo
