Algoritmo "Lista_compras"

Var

   N, i : inteiro
   Total: real
   Item: vetor [0..99] de caractere
   
Inicio

    escreva ("Quantos itens irá comprar? ")
    leia (N)
    
    para i de 0 ate n-1 faca
      escreval ("Item ", i+1)
      escreva ("Nome: ")
      leia (Item [i])
      escreval ("TipoMedida: KG")
      escreva ("Preco: R$ ")
      leia (Item[i])
      escreva ("Quantidade: ")
      leia (item[i])
      escreval
    fimpara

    Total <-
Fimalgoritmo


