Algoritmo "TERRENO"



Var
    Largura, comprimento, metroQuadrado, area, preco: real
    

Inicio

      Escreva ("Digite a largura do terreno: ")
      leia(largura)
      Escreva ("Digite o Comprimento do terreno: ")
      leia(comprimento)
      Escreva ("Digite o valor do metro quadrado: ")
      leia(metroQuadrado)
      
      area <- largura * comprimento
      preco <- area * metroQuadrado
      escreval
      Escreval ("area do terreno = ", area:8:2)
      escreval ("preco do terreno = ", preco: 8:2)

Fimalgoritmo